name: run-walkthroughs
on:
  push:
    branches:
      staging
jobs:
  databricks81-walkthrough:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - shell: bash
        env:
          DATABRICKS_ADDRESS: ${{ secrets.DATABRICKS_ADDRESS }}
          DATABRICKS_API_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}
        run: ./rehearsals/databricks8.1/drop_create/routine.sh